/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author FabuAndrásNorbert(SZ
 */
public class halallabirintus extends javax.swing.JFrame {

    /**
     * Creates new form halallabirintus
     */
    public halallabirintus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tpaneJatek = new javax.swing.JTabbedPane();
        jpnKezdolap = new javax.swing.JPanel();
        lblKep = new javax.swing.JLabel();
        btnJatekGomb = new javax.swing.JButton();
        pnlFerfi = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlNoi = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlKepessegek = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpnElsooldal = new javax.swing.JPanel();
        lblKep2 = new javax.swing.JLabel();
        pnlSzoveg1 = new javax.swing.JPanel();
        jscpSzoveg1 = new javax.swing.JScrollPane();
        txtpSzoveg1 = new javax.swing.JTextPane();
        btn270oldal = new javax.swing.JButton();
        btn66oldal = new javax.swing.JButton();
        lblLada = new javax.swing.JLabel();
        lblLada2 = new javax.swing.JLabel();
        jpnMasodikoldal = new javax.swing.JPanel();
        lblKep3 = new javax.swing.JLabel();
        pnlSzoveg2 = new javax.swing.JPanel();
        jscpSzoveg2 = new javax.swing.JScrollPane();
        txtpSzoveg2 = new javax.swing.JTextPane();
        btn215oldal = new javax.swing.JButton();
        btn373oldal = new javax.swing.JButton();
        lblLada3 = new javax.swing.JLabel();
        lblLada4 = new javax.swing.JLabel();
        mbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tpaneJatek.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpnKezdolap.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblKep.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\NetBeansProjects\\320Magas\\menű 1.png")); // NOI18N
        lblKep.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnJatekGomb.setText("Új Játék");
        btnJatekGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJatekGombActionPerformed(evt);
            }
        });

        pnlFerfi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Féfi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jButton3.setText("Választ");
        buttonGroup1.add(jButton3);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\NetBeansProjects\\320Magas\\ferfi.jpg")); // NOI18N

        javax.swing.GroupLayout pnlFerfiLayout = new javax.swing.GroupLayout(pnlFerfi);
        pnlFerfi.setLayout(pnlFerfiLayout);
        pnlFerfiLayout.setHorizontalGroup(
            pnlFerfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFerfiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlFerfiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFerfiLayout.setVerticalGroup(
            pnlFerfiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFerfiLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        pnlNoi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Női", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jButton2.setText("Választ");
        buttonGroup1.add(jButton2);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\NetBeansProjects\\320Magas\\noi.jpg")); // NOI18N

        javax.swing.GroupLayout pnlNoiLayout = new javax.swing.GroupLayout(pnlNoi);
        pnlNoi.setLayout(pnlNoiLayout);
        pnlNoiLayout.setHorizontalGroup(
            pnlNoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNoiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlNoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addGroup(pnlNoiLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlNoiLayout.setVerticalGroup(
            pnlNoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNoiLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pnlKepessegek.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Képességek", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Ügyesség: 0. [szint]");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Szerencse: 0 [db]");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Életerő: 3 [élet]");

        javax.swing.GroupLayout pnlKepessegekLayout = new javax.swing.GroupLayout(pnlKepessegek);
        pnlKepessegek.setLayout(pnlKepessegekLayout);
        pnlKepessegekLayout.setHorizontalGroup(
            pnlKepessegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKepessegekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKepessegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlKepessegekLayout.setVerticalGroup(
            pnlKepessegekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKepessegekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnKezdolapLayout = new javax.swing.GroupLayout(jpnKezdolap);
        jpnKezdolap.setLayout(jpnKezdolapLayout);
        jpnKezdolapLayout.setHorizontalGroup(
            jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKezdolapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnJatekGomb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpnKezdolapLayout.createSequentialGroup()
                        .addComponent(pnlNoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlFerfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlKepessegek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnKezdolapLayout.setVerticalGroup(
            jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnKezdolapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnKezdolapLayout.createSequentialGroup()
                        .addComponent(lblKep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnJatekGomb, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jpnKezdolapLayout.createSequentialGroup()
                        .addGroup(jpnKezdolapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlFerfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlNoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlKepessegek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tpaneJatek.addTab("Kezdőoldal", jpnKezdolap);

        lblKep2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\1. oldal.png")); // NOI18N

        pnlSzoveg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtpSzoveg1.setContentType("text/html"); // NOI18N
        txtpSzoveg1.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \rMiután öt percet haladtál lassan az alagútban,<br>\negy kőasztalhoz érsz,<br>\namely a bal oldali fal mellett áll.<br>\nHat doboz van rajta,<br>\negyikükre a te neved festették.<br>\nHa kiakarod nyitni a dobozt,<br>\nlapozz a 270-re.<br>\nHa inkább tovább haladsz észak felé,<br>\nlapozz a 66-ra.\n    </p>\r\n  </body>\r\n</html>\r\n");
        jscpSzoveg1.setViewportView(txtpSzoveg1);

        btn270oldal.setText("270. oldal");
        buttonGroup2.add(btn270oldal);

        btn66oldal.setText("66. oldal");
        buttonGroup2.add(btn66oldal);

        lblLada.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\1864535_stock-photo-treasure-chest.jpg")); // NOI18N

        lblLada2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\1864535_stock-photo-treasure-chest.jpg")); // NOI18N

        javax.swing.GroupLayout pnlSzoveg1Layout = new javax.swing.GroupLayout(pnlSzoveg1);
        pnlSzoveg1.setLayout(pnlSzoveg1Layout);
        pnlSzoveg1Layout.setHorizontalGroup(
            pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzoveg1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpSzoveg1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlSzoveg1Layout.createSequentialGroup()
                        .addGroup(pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btn66oldal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn270oldal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(lblLada2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlSzoveg1Layout.setVerticalGroup(
            pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzoveg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpSzoveg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLada2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlSzoveg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn66oldal)
                    .addComponent(btn270oldal))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnElsooldalLayout = new javax.swing.GroupLayout(jpnElsooldal);
        jpnElsooldal.setLayout(jpnElsooldalLayout);
        jpnElsooldalLayout.setHorizontalGroup(
            jpnElsooldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnElsooldalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKep2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSzoveg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnElsooldalLayout.setVerticalGroup(
            jpnElsooldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnElsooldalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnElsooldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSzoveg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKep2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpaneJatek.addTab("1. oldal", jpnElsooldal);

        lblKep3.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\56. oldal.png")); // NOI18N

        pnlSzoveg2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtpSzoveg2.setContentType("text/html"); // NOI18N
        txtpSzoveg2.setText("<html>\r\n  <head>\r\n\r\n  </head>\r\n  <body>\r\n    <p style=\"margin-top: 0\">\r\n      \rLátod, hogy az akadály egy széles,<br>\nbarna, sziklaszerű tárgy.<br>\nMegérinted, és meglepve tapasztalod,<br>\nhogy lágy, szivacsszerű.<br>\nHa át szeretnél mászni rajta, lapozz a 373-ra.<br>\nHa ketté akarod vágni a kardoddal,<br>\nlapozz a 215-re.\n    </p>\r\n  </body>\r\n</html>\r\n");
        jscpSzoveg2.setViewportView(txtpSzoveg2);

        btn215oldal.setText("215. oldal");

        btn373oldal.setText("373. oldal");

        lblLada3.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\1864535_stock-photo-treasure-chest.jpg")); // NOI18N

        lblLada4.setIcon(new javax.swing.ImageIcon("C:\\Users\\FabuAndrásNorbert(SZ\\Documents\\halallabirintus_2023_11_30\\kepek\\1864535_stock-photo-treasure-chest.jpg")); // NOI18N

        javax.swing.GroupLayout pnlSzoveg2Layout = new javax.swing.GroupLayout(pnlSzoveg2);
        pnlSzoveg2.setLayout(pnlSzoveg2Layout);
        pnlSzoveg2Layout.setHorizontalGroup(
            pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzoveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jscpSzoveg2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlSzoveg2Layout.createSequentialGroup()
                        .addGroup(pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLada3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btn215oldal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn373oldal, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(lblLada4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnlSzoveg2Layout.setVerticalGroup(
            pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSzoveg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscpSzoveg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLada3)
                    .addComponent(lblLada4))
                .addGap(18, 18, 18)
                .addGroup(pnlSzoveg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn215oldal)
                    .addComponent(btn373oldal))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnMasodikoldalLayout = new javax.swing.GroupLayout(jpnMasodikoldal);
        jpnMasodikoldal.setLayout(jpnMasodikoldalLayout);
        jpnMasodikoldalLayout.setHorizontalGroup(
            jpnMasodikoldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMasodikoldalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKep3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSzoveg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnMasodikoldalLayout.setVerticalGroup(
            jpnMasodikoldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMasodikoldalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMasodikoldalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlSzoveg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblKep3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        tpaneJatek.addTab("56. oldal", jpnMasodikoldal);

        jMenu1.setText("Beállítások");

        jMenuItem1.setText("Megnyitás");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Kilépés");
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem3.setText("Mentés");
        jMenu1.add(jMenuItem3);

        mbMenu.add(jMenu1);

        jMenu2.setText(".....");
        mbMenu.add(jMenu2);

        setJMenuBar(mbMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpaneJatek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpaneJatek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJatekGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJatekGombActionPerformed
        tpaneJatek.setSelectedIndex(1 );
    }//GEN-LAST:event_btnJatekGombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Halallabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halallabirintus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn215oldal;
    private javax.swing.JButton btn270oldal;
    private javax.swing.JButton btn373oldal;
    private javax.swing.JButton btn66oldal;
    private javax.swing.JButton btnJatekGomb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel jpnElsooldal;
    private javax.swing.JPanel jpnKezdolap;
    private javax.swing.JPanel jpnMasodikoldal;
    private javax.swing.JScrollPane jscpSzoveg1;
    private javax.swing.JScrollPane jscpSzoveg2;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblKep2;
    private javax.swing.JLabel lblKep3;
    private javax.swing.JLabel lblLada;
    private javax.swing.JLabel lblLada2;
    private javax.swing.JLabel lblLada3;
    private javax.swing.JLabel lblLada4;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JPanel pnlFerfi;
    private javax.swing.JPanel pnlKepessegek;
    private javax.swing.JPanel pnlNoi;
    private javax.swing.JPanel pnlSzoveg1;
    private javax.swing.JPanel pnlSzoveg2;
    private javax.swing.JTabbedPane tpaneJatek;
    private javax.swing.JTextPane txtpSzoveg1;
    private javax.swing.JTextPane txtpSzoveg2;
    // End of variables declaration//GEN-END:variables
}
